#!/bin/bash

# Options
merge="merge selected into current"
rebase="rebase current onto selected"

br=$(git branch -r --format='%(refname:short)' | fzf)
op=$(printf "$merge\n$rebase" | fzf)

if [ "$op" == "$merge" ]
then 
    git merge $br
elif [ "$op" == "$rebase" ]
then
    git rebase --onto $br $(git branch --show) 
fi
