#!/bin/bash

# Script to select a branch and an
# action to do with the selected branch.
#
# Scripts accepts arguments for branch selection see $a.

# Options
merge="merge selected into current"
rebase="rebase current onto selected"

a="-r"

if [ "$#" -gt 0 ]
then
    a=$@
fi

br=$(git branch $a --format='%(refname:short)' | fzf)

if [ -z "$br" ]
then
    exit 1
fi

op=$(printf "$merge\n$rebase" | fzf)

if [ "$op" == "$merge" ]
then 
    git merge $br
elif [ "$op" == "$rebase" ]
then
    git rebase --onto $br $(git branch --show) 
fi
